---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant

    tasks:
      - name: Create directory for ssh-keys
        file: state=directory mode=0700 dest=/root/.ssh/

      - name: Install prerequisites for Docker repository
        apt:
          name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
          update_cache: yes

      - name: Add Docker GPG key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg

      - name: Add Docker APT repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

      - name: Install Docker CE
        apt:
          name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
          update_cache: yes

      - name: Install prerequisites for docker-compose
        apt:
          name: ['python3-pip', 'python3-setuptools', 'virtualenv']

      - name: Enable docker daemon
        systemd:
          name: docker
          state: started
          enabled: yes

      - name: Install docker-compose
        pip:
          name: docker-compose

      - name: Synchronization
        copy:
          src: ../stack/
          dest: "/opt/stack/"
          owner: root
          group: root
          mode: 0644
        become: true

      - name: Pull all images in compose
        command: docker-compose -f /opt/stack/docker-compose.yaml pull

      - name: Up all services in compose
        command: docker-compose -f /opt/stack/docker-compose.yaml up -d