version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
      - ~/config/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=mytst_db
      - MYSQL_ROOT_PASSWORD=mysh
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=test_user
