 Vagrant.configure("2") do |config|
    config.vm.network "forwarded_port", guest: 19999, host: 19999, auto_correct: true
 config.vm.box = "bento/ubuntu-20.04"
    config.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.cpus = 1
   end
 end