Vagrant.configure("2") do |config|
    config.vm.network "forwarded_port", guest: 80, host: 80, id: "nginx"
    config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
    config.vm.hostname = "server"
    config.vm.network "private_network", ip: "192.168.50.10"
    config.vm.synced_folder "html/", "/var/www/html"
    #config.vm.provision "shell", path: "provision.sh"
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.box_version = "3.1.16"
    config.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.cpus = 1
   end
 end


 #Vagrant.configure("2") do |config|
 # config.vm.network "forwarded_port", guest: 19999, host: 19999, auto_correct: true
 # config.vm.box = "bento/ubuntu-20.04"
 # config.vm.provider :virtualbox do |vb|
 #   lvm_experiments_disk0_path = "/tmp/lvm_experiments_disk0.vmdk"
 #   lvm_experiments_disk1_path = "/tmp/lvm_experiments_disk1.vmdk"
 #   vb.customize ['createmedium', '--filename', lvm_experiments_disk0_path, '--size', 2560]
 #   vb.customize ['createmedium', '--filename', lvm_experiments_disk1_path, '--size', 2560]
 #   vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', lvm_experiments_disk0_path]
 #   vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', lvm_experiments_disk1_path]
 # end
#end