---
# defaults file for proxy_server
nginx_revproxy_sites:
  www.:
    domains:
      - www.myshelov.site
      - myshelov.site
    upstreams:
      - { backend_address: "{{ lookup ('env', 'node04_app_private') }}", backend_port: 80 }   #app_to_www
    ssl: true
    letsencrypt: true
    letsencrypt_email: "viktor@myshelov.site"
  grafana.myshelov.site:
    domains:
      - grafana.myshelov.site
    upstreams:
      - { backend_address: "{{ lookup ('env', 'node07_monitoring_private') }}", backend_port: 3000 }  #monitoring_grafana
    ssl: true
    letsencrypt: true
    letsencrypt_email: "viktor@myshelov.site"
  prometheus.myshelov.site:
    domains:
      - prometheus.myshelov.site
    upstreams:
      - { backend_address: "{{ lookup ('env', 'node07_monitoring_private') }}", backend_port: 9090 }  #monitoring_prometheus
    ssl: true
    letsencrypt: true
    letsencrypt_email: "viktor@myshelov.site"
  alertmanager.myshelov.site:
    domains:
      - alertmanager.myshelov.site
    upstreams:
      - { backend_address: "{{ lookup ('env', 'node07_monitoring_private') }}", backend_port: 9093 }  #monitoring_alertmanager
    ssl: true
    letsencrypt: true
    letsencrypt_email: "viktor@myshelov.site"
  gitlab.myshelov.site:
    domains:
      - gitlab.myshelov.site
    upstreams:
      - { backend_address: "{{ lookup ('env', 'node05_gitlab_private') }}", backend_port: 80 }   #gitlab_to_gitlab
    ssl: true
    letsencrypt: true
    letsencrypt_email: "viktor@myshelov.site"