ISO = "bento/ubuntu-20.04"
NET = "172.31.21."
DOMAIN = ".netology"
HOST_PREFIX = "server"

servers = [
  {
    :hostname => HOST_PREFIX + "2" + DOMAIN,
    :ip => NET + "11",
    :ssh_host => "20011",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/08-ansible-01-base/src/vagrant", disabled: true
  config.vm.synced_folder "../stack", "/stack"
  config.vm.synced_folder "../playbook", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"]
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/stack/docker-compose.yml", rebuild: true, run: "always"
  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.limit = "all"
    ansible.vault_password_file = "/vagrant/ansible_vault_key"
    ansible.inventory_path = "inventory/prod.yml"
    ansible.playbook = "/vagrant/site.yml"
    ansible.playbook_command = "sudo ansible-playbook"
    ansible.install_mode = "pip"
    ansible.pip_install_cmd  = "until sudo apt update ; do sleep 1 ; done && sudo apt install -y python3-pip && sudo rm -f /usr/bin/pip && sudo ln -s /usr/bin/pip3 /usr/bin/pip && sudo -H pip install --upgrade pip"
    #ansible.version = "2.13.4"
    #ansible.extra_vars = { ansible_user: 'vagrant' }
  end
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:hostname]
      end
    end
  end
end